name: esacc_task
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  google_sign_in: ^6.1.6
  font_awesome_flutter: ^10.7.0
  equatable: ^2.0.5
  get_it: ^7.6.7
  flutter_screenutil: ^5.9.0
  flutter_bloc: ^8.1.4
  bloc: ^8.1.3
  connectivity_plus: ^5.0.2
  fluttertoast: ^8.2.4
  dropdown_button2: ^2.3.9
  permission_handler: ^11.0.1
  flutter_facebook_auth: ^6.1.1
  webview_flutter: ^4.5.0
  flutter_blue_plus: ^1.31.15
  flutter_svg: ^2.0.10+1
  flutter_nearby_connections: ^1.1.2
  device_info_plus: ^9.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/login.svg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

